### ISSUE TITLE
Cooling FAN for filament 

### ISSUE THREAD

**Issue by xarbit** [emilio1625/Anycubic-Kossel-Marlin#9]
I Installed this firmware to my Anycubic Kossel Linear Plus (upgraded).
I am havining a issue with the part cooling fan, it is not turning on when I start my print. 
Do you know what I might be doing wrong? I looked in all settings in Configuration.h but I coulndt find anything.

When I print I always have to go manually in the printer and crank the speed value of "FAN speed 1" up to 255.

Thanks

**Comment by SergioSV96** [comment]
Did you find a solution? I am having the same problem, thank you.

**Comment by SergioSV96** [comment]
> I Installed this firmware to my Anycubic Kossel Linear Plus (upgraded).
> I am havining a issue with the part cooling fan, it is not turning on when I start my print.
> Do you know what I might be doing wrong? I looked in all settings in Configuration.h but I coulndt find anything.
> 
> When I print I always have to go manually in the printer and crank the speed value of "FAN speed 1" up to 255.
> 
> Thanks

Did you find a solution? I am having the same problem, thank you.

**Comment by xarbit** [comment]
Yes because I used my printer alot, but honestly I cannot remember if it was because the trigorilla board was broken or because I created my own firmware. I had a few burnt mosfets and switched the board a few times. 

https://github.com/xarbit/Marlin_119_Anycubic_Kossel_Linear_Plus
